/** LLM 生成的单词 SVG 清单 — 由 npm run generate:word-svgs 自动更新 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { PICTURABLE_WORDS } from '../../src/components/concept/PicturableWordVisual';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const MANIFEST_TS = path.join(__dirname, '../../src/data/wordSvgManifest.ts');
const APPROVED_JSON = path.join(__dirname, '../../Designs/audit/word-svg-approved.json');

const PICTURABLE_SET = new Set<string>(PICTURABLE_WORDS as readonly string[]);

export function loadApprovedIds(): string[] {
  if (fs.existsSync(APPROVED_JSON)) {
    return JSON.parse(fs.readFileSync(APPROVED_JSON, 'utf8')) as string[];
  }
  return [];
}

export function saveApprovedIds(ids: string[]) {
  fs.mkdirSync(path.dirname(APPROVED_JSON), { recursive: true });
  fs.writeFileSync(APPROVED_JSON, JSON.stringify([...new Set(ids)].sort(), null, 2), 'utf8');
}

/** picturable 的 v1 烂图默认不批准；仅 legacy 非 picturable 自动批准 */
export function bootstrapApproved(ids: string[]): string[] {
  const existing = new Set(loadApprovedIds());
  for (const id of ids) {
    if (!PICTURABLE_SET.has(id)) existing.add(id);
  }
  return [...existing].sort();
}

export function approveWord(id: string) {
  const next = new Set(loadApprovedIds());
  next.add(id.toLowerCase());
  saveApprovedIds([...next].sort());
}

export function writeWordSvgManifest(outDir: string, approvedOverride?: string[]) {
  const ids = fs
    .readdirSync(outDir)
    .filter((f) => f.endsWith('.svg'))
    .map((f) => f.replace(/\.svg$/i, ''))
    .sort();

  const approved = (approvedOverride ?? bootstrapApproved(ids)).filter((id) => ids.includes(id));

  saveApprovedIds(approved);

  const body = `/** AUTO-GENERATED by scripts/generate-word-svgs.ts — do not edit */
import { PICTURABLE_WORDS } from '../components/concept/PicturableWordVisual';

export const WORD_SVG_IDS = ${JSON.stringify(ids, null, 2)} as const;

export const WORD_SVG_APPROVED_IDS = ${JSON.stringify(approved, null, 2)} as const;

const WORD_SVG_SET = new Set<string>(WORD_SVG_IDS);
const WORD_SVG_APPROVED = new Set<string>(WORD_SVG_APPROVED_IDS);
const PICTURABLE_SET = new Set<string>(PICTURABLE_WORDS as readonly string[]);

/** 仅 approved 词走静态图；picturable 必须 v2 过关才批准 */
export function hasWordSvg(wordId: string): boolean {
  const id = wordId.toLowerCase();
  if (!WORD_SVG_APPROVED.has(id)) return false;
  if (PICTURABLE_SET.has(id) && !WORD_SVG_APPROVED.has(id)) return false;
  return WORD_SVG_SET.has(id);
}

export function wordSvgSrc(wordId: string): string {
  return \`/assets/word-img/\${wordId.toLowerCase()}.svg\`;
}
`;

  fs.writeFileSync(MANIFEST_TS, body, 'utf8');

  const listJson = path.join(outDir, '../../word-svg-list.json');
  fs.writeFileSync(listJson, JSON.stringify(ids, null, 2), 'utf8');
}

export function ensureWordSvgManifest() {
  if (!fs.existsSync(MANIFEST_TS)) {
    writeWordSvgManifest(path.join(__dirname, '../../public/assets/word-img'));
  }
}
