/**
 * Cursor GenerateImage 提示词表 — 与 come.png 风格一致。
 * 用法：在 Cursor 中对每个词调用 GenerateImage，保存到 public/assets/word-img/{slug}.png
 * 完成后运行：npm run sync:word-png-manifest
 * 重新生成：npx tsx scripts/build-word-png-prompts.ts
 */

export const WORD_ILLUSTRATION_STYLE =
  'Light flat vector illustration, soft pastel colors, clean minimal style, single clear concept centered, pure white background #FFFFFF, no border, no frame, no drop shadow, no rounded card inside image, subject only on white, no text, no labels, no watermark, friendly educational flashcard style';

export const OPERATOR_PROMPTS: Record<string, string> = {
  be: 'A person standing calmly present in a peaceful scene, existence and being, flat vector pastel illustration',
  come: 'A simple person walking toward the viewer with welcoming gesture, approaching motion, flat vector pastel illustration',
  do: 'A person actively performing a task with tools, doing action in progress, flat vector pastel illustration',
  get: 'A hand reaching out to receive a small gift box from another hand, receiving action, flat vector pastel illustration',
  give: 'One hand offering a small gift box to another hand, giving action, flat vector pastel illustration',
  go: 'A simple person walking away from viewer into distance, departure motion, flat vector pastel illustration',
  have: 'A person holding a small bag of possessions, having ownership, flat vector pastel illustration',
  keep: 'Hands holding a small treasure box close to chest, keeping safe, flat vector pastel illustration',
  let: 'An open gate or door allowing passage through, permission to pass, flat vector pastel illustration',
  make: 'Hands crafting or assembling blocks into a shape, creating something, flat vector pastel illustration',
  may: 'An open doorway with soft light suggesting possibility and permission, flat vector pastel illustration',
  put: 'A hand placing an object down onto a table surface, putting down action, flat vector pastel illustration',
  say: 'A person speaking with speech bubble containing sound waves, saying words, flat vector pastel illustration',
  see: 'A large friendly eye looking at a colorful butterfly, seeing and observing, flat vector pastel illustration',
  seem: 'Two similar objects side by side one solid one ghostly outline, appearance versus reality, flat vector pastel illustration',
  send: 'A paper airplane flying from one hand toward distant mailbox, sending message, flat vector pastel illustration',
  take: 'A hand lifting an object up from a table, taking action, flat vector pastel illustration',
  will: 'A person pointing forward toward a bright future path, determination and future intent, flat vector pastel illustration',
};

export const PICTURABLE_PROMPTS: Record<string, string> = {
  angle: 'A right angle corner shape with degree arc, geometry angle',
  ant: 'A small black ant with six legs, insect',
  apple: 'A red apple with green leaf, simple fruit icon, flat vector pastel illustration',
  arch: 'A stone arch bridge curve, architecture arch',
  arm: 'A human arm from shoulder to hand, body part',
  army: 'A row of toy soldiers in uniform, military group',
  baby: 'A cute baby in onesie sitting, infant',
  bag: 'A brown paper shopping bag with handles, carry bag',
  ball: 'A colorful striped playground ball, toy icon, flat vector pastel illustration',
  band: 'A musical band with drum and trumpet, music group',
  basin: 'A white wash basin sink bowl, bathroom basin',
  basket: 'A woven wicker basket with handle, container',
  bath: 'A bathtub with bubbles and rubber duck, bathing',
  bed: 'A cozy bed with pillow and blanket, furniture',
  bee: 'A yellow and black striped bee with wings, insect',
  bell: 'A golden school bell with clapper, ringing bell',
  berry: 'A cluster of red berries on stem, fruit',
  bird: 'A small blue bird perched on branch, animal icon, flat vector pastel illustration',
  blade: 'A sharp knife blade edge close-up, cutting blade',
  board: 'A wooden cutting board flat surface, plank board',
  boat: 'A small sailboat on calm water, vessel',
  bone: 'A white dog bone shape, skeleton bone',
  book: 'An open book with visible pages, reading icon, flat vector pastel illustration',
  boot: 'A brown leather boot with laces, footwear',
  bottle: 'A glass bottle with cork stopper, container',
  box: 'A cardboard box with flaps open, package',
  boy: 'A young boy with backpack smiling, child',
  brain: 'A pink brain organ illustration, anatomy',
  brake: 'A bicycle brake lever and wheel slowing down, vehicle brake icon, flat vector pastel illustration',
  branch: 'A tree branch with green leaves, plant part',
  brick: 'A single red clay brick, building material',
  bridge: 'A simple arch bridge over river, structure',
  brush: 'A paintbrush with colorful bristles, tool',
  bucket: 'A metal bucket with handle, container',
  bulb: 'A light bulb glowing yellow, electric lamp',
  button: 'A round shirt button with thread holes, fastener',
  cake: 'A layered birthday cake with candle, dessert',
  camera: 'A vintage camera with lens, photography',
  card: 'A playing card ace of hearts, card',
  carriage: 'A horse-drawn carriage coach, vehicle',
  cart: 'A wooden wheelbarrow cart, wagon',
  cat: 'A cute orange tabby cat sitting, simple pet icon, flat vector pastel illustration',
  chain: 'A metal chain links connected, chain',
  cheese: 'A wedge of yellow Swiss cheese, dairy food',
  chest: 'A wooden treasure chest with gold coins, storage',
  chin: 'A face profile showing chin jawline, body part',
  church: 'A small church building with steeple cross, building',
  circle: 'A perfect circle shape with soft fill, geometry',
  clock: 'A round wall clock showing three o clock, time icon, flat vector pastel illustration',
  cloud: 'A fluffy white cloud in sky, weather',
  coat: 'A winter coat jacket on hanger, clothing',
  collar: 'A shirt collar with button, clothing part',
  comb: 'A hair comb with teeth, grooming tool',
  cord: 'A coiled electrical cord plug, cable',
  cow: 'A black and white dairy cow standing, farm animal',
  cup: 'A ceramic tea cup with steam, drinkware icon, flat vector pastel illustration',
  curtain: 'Window curtains draped open, home decor',
  cushion: 'A soft square sofa cushion pillow, furniture',
  dog: 'A friendly golden dog sitting with tongue out, simple pet icon, flat vector pastel illustration',
  door: 'A wooden door with round knob, entrance',
  drain: 'A floor drain grate with water flowing, plumbing',
  drawer: 'An open dresser drawer with clothes, furniture',
  dress: 'A blue summer dress on hanger, clothing',
  drop: 'A single water droplet falling, liquid drop',
  ear: 'A human ear close-up illustration, body part',
  egg: 'A brown egg in nest, food',
  engine: 'A car engine motor with pistons, machine',
  eye: 'A friendly human eye with iris, body part',
  face: 'A smiling human face front view, body part',
  farm: 'A farm with barn silo and fields, rural scene',
  feather: 'A soft bird feather quill, nature',
  finger: 'A pointing index finger hand, body part',
  fish: 'An orange goldfish swimming, aquatic animal icon, flat vector pastel illustration',
  flag: 'A waving national flag on pole, banner',
  floor: 'Wooden floor planks pattern, surface',
  fly: 'A housefly insect with wings, bug',
  foot: 'A human foot sole view, body part',
  fork: 'A silver dining fork utensil, cutlery',
  fowl: 'A rooster chicken farm bird, poultry',
  frame: 'A picture frame with landscape photo, border',
  garden: 'A flower garden with tulips and fence, outdoor',
  girl: 'A young girl with ponytail smiling, child',
  glove: 'A winter mitten glove pair, clothing',
  goat: 'A white goat with horns on grass, farm animal',
  gun: 'A simple toy water pistol gun, not realistic weapon',
  hair: 'Flowing brown hair strands, body part',
  hammer: 'A claw hammer tool with wooden handle, tool',
  hand: 'An open human hand palm up, body part',
  hat: 'A straw sun hat with ribbon, headwear',
  head: 'A human head profile silhouette, body part',
  heart: 'A red heart shape, love symbol icon, flat vector pastel illustration',
  hook: 'A metal hook for hanging coat, fastener',
  horn: 'A ram animal horn curved, body part',
  horse: 'A brown horse standing in profile, farm animal icon, flat vector pastel illustration',
  hospital: 'A hospital building with red cross sign, building',
  house: 'A cozy small house with red roof and chimney, home icon, flat vector pastel illustration',
  island: 'A small tropical island with palm tree in ocean, land',
  jewel: 'A sparkling diamond gem ring, jewelry',
  kettle: 'A whistling tea kettle on stove, kitchenware',
  key: 'A golden old-fashioned key, lock key',
  knee: 'A bent knee joint leg illustration, body part',
  knife: 'A kitchen chef knife with blade, utensil',
  knot: 'A rope tied in overhand knot, binding',
  leaf: 'A green maple leaf, plant part',
  leg: 'A human leg from hip to foot, body part',
  library: 'A bookshelf library with stacked books, building',
  line: 'A straight horizontal line with endpoints, geometry',
  lip: 'Lips with slight smile close-up, body part',
  lock: 'A padlock locked shut with keyhole, security',
  map: 'A folded paper map with routes, navigation',
  match: 'A wooden matchstick with flame lit, fire',
  monkey: 'A cute brown monkey sitting, primate',
  moon: 'A crescent moon with soft stars, night sky icon, flat vector pastel illustration',
  mouth: 'An open mouth showing teeth smile, body part',
  muscle: 'A flexed arm showing bicep muscle, anatomy',
  nail: 'A metal construction nail, fastener',
  neck: 'A neck connecting head to shoulders, body part',
  needle: 'A sewing needle with thread, tool',
  nerve: 'A nerve cell neuron with dendrites, anatomy',
  net: 'A fishing net with mesh pattern, tool',
  nose: 'A human nose front view, body part',
  nut: 'A walnut nut in shell cracked open, food',
  office: 'An office desk with computer and chair, workplace',
  orange: 'A whole orange fruit with leaf, citrus',
  oven: 'A kitchen oven with door and knobs, appliance',
  parcel: 'A wrapped brown parcel package with string, mail',
  pen: 'A blue ballpoint pen, writing tool',
  pencil: 'A yellow wooden pencil with eraser, writing tool',
  picture: 'A framed landscape painting on wall, artwork',
  pig: 'A pink pig farm animal, livestock',
  pin: 'A red push pin thumbtack, fastener',
  pipe: 'A smoking pipe or water pipe tube, tube',
  plane: 'A passenger airplane in flight, aircraft',
  plate: 'A white dinner plate empty, dishware',
  plough: 'A farm plough behind horse, agriculture tool',
  pocket: 'A jeans pocket with hand inside, clothing part',
  pot: 'A cooking pot with lid on stove, kitchenware',
  potato: 'A brown potato with eyes, vegetable',
  prison: 'A prison building with barred window, institution',
  pump: 'A water hand pump with handle, machine',
  rail: 'A train rail track with wooden ties, transport',
  rat: 'A small gray rat with tail, rodent',
  receipt: 'A paper store receipt with lines, document',
  ring: 'A gold wedding ring band, jewelry',
  rod: 'A fishing rod with line, tool',
  roof: 'A house roof with red tiles and chimney, building part',
  root: 'Plant roots underground with soil, plant part',
  sail: 'A white sail on boat mast, nautical',
  school: 'A school building with clock tower, institution',
  scissors: 'A pair of open scissors, cutting tool',
  screw: 'A metal screw with threads, fastener',
  seed: 'A small plant seed sprouting green shoot, botany',
  sheep: 'A fluffy white sheep on grass, farm animal',
  shelf: 'A wooden wall shelf with books, furniture',
  ship: 'A large cargo ship on ocean, vessel',
  shirt: 'A folded blue button shirt, clothing',
  shoe: 'A single sneaker shoe side view, footwear',
  skin: 'A patch of human skin texture, body part',
  skirt: 'A pleated skirt on hanger, clothing',
  snake: 'A green coiled snake, reptile',
  sock: 'A striped pair of socks, clothing',
  spade: 'A garden spade shovel tool, gardening',
  sponge: 'A yellow kitchen sponge with bubbles, cleaning',
  spoon: 'A silver soup spoon utensil, cutlery',
  spring: 'A metal coil spring bouncing, mechanism',
  square: 'A perfect square shape with soft fill, geometry',
  stamp: 'A postage stamp with perforated edges, mail',
  star: 'A five-pointed golden star shape, astronomy',
  station: 'A train station platform with sign, transport hub',
  stem: 'A flower stem with leaves no bloom, plant part',
  stick: 'A wooden walking stick branch, nature',
  stocking: 'A Christmas stocking hung by fireplace, clothing',
  stomach: 'A stomach organ anatomy illustration, body part',
  store: 'A small corner shop storefront, retail',
  street: 'A city street with buildings and road, urban',
  sun: 'A bright yellow sun with soft rays, weather icon, flat vector pastel illustration',
  table: 'A wooden dining table with four legs, furniture',
  tail: 'A dog wagging tail rear view, animal part',
  thread: 'A spool of sewing thread with needle, craft',
  throat: 'A throat neck anatomy cross-section, body part',
  thumb: 'A thumbs up hand gesture, body part',
  ticket: 'A concert admission ticket stub, document',
  toe: 'Human toes on foot close-up, body part',
  tongue: 'A tongue sticking out playfully, body part',
  tooth: 'A white molar tooth illustration, dentistry',
  town: 'A small town with houses and church steeple, settlement',
  train: 'A passenger train on tracks, vehicle',
  tray: 'A serving tray with cup and plate, dishware',
  tree: 'A green tree with brown trunk, nature icon, flat vector pastel illustration',
  trousers: 'A pair of folded pants trousers, clothing',
  umbrella: 'An open rain umbrella colorful, weather gear',
  wall: 'A brick wall section pattern, structure',
  watch: 'A wristwatch with round face, timepiece',
  wheel: 'A wooden wagon wheel with spokes, vehicle part',
  whip: 'A coiled leather whip, tool',
  whistle: 'A silver referee whistle on lanyard, tool',
  window: 'A window with curtains and sunny view, building part',
  wing: 'A bird wing feather spread, animal part',
  wire: 'A bent copper electrical wire, material',
  worm: 'A pink earthworm in soil, creature',
};

export const DIRECTION_PROMPTS: Record<string, string> = {
  about: 'A small planet with orbiting dots circling around it, about and around icon',
  across: 'A person walking across a zebra crosswalk from one side to other, across crossing icon',
  after: 'Two runners on a track with second person behind first, after and following icon',
  against: 'A ladder leaning against a brick wall with contact pressure, against wall icon',
  among: 'A single figure standing in the middle of a small crowd of people, among group icon',
  as: 'A person wearing a chef hat acting as a cook role, as role identity icon',
  at: 'A red pin marker on a map pinpointing an exact spot, location point icon',
  before: 'Two runners on a track with first person ahead of second, before and leading icon',
  between: 'A ball squeezed in the narrow gap between two bookends, between two things icon',
  by: 'A person standing beside a lamppost on a sidewalk, next-to icon',
  down: 'A leaf falling downward with gentle downward motion lines, down direction icon',
  for: 'A wrapped gift box with ribbon meant for someone, for purpose and recipient icon',
  from: 'A dotted path arrow starting from a house and pointing outward away, from origin icon',
  in: 'A small ball inside a transparent box container, inside relationship icon',
  of: 'A slice of pie separated from whole pie showing part-of relationship, of belonging icon',
  off: 'A hat lifted off a table showing separation gap, off and away from surface icon',
  on: 'A book resting on top of a wooden table surface, on-top contact icon',
  over: 'A bird flying above a house with clear air gap between them, over position icon',
  than: 'A balance scale comparing a big apple versus small apple, than comparison icon',
  through: 'A ball passing through a tunnel pipe from one end to the other, through passage icon',
  till: 'A timeline bar extending to a finish flag endpoint, till boundary icon',
  to: 'A dotted path arrow leading toward a house destination flag, toward goal icon',
  under: 'A cat hiding beneath a bed with visible gap below furniture, under position icon',
  up: 'A balloon rising upward with upward motion lines against sky, up direction icon',
  with: 'Two friends walking side by side together holding hands, with and together icon',
};

export const GENERAL_PROMPTS: Record<string, string> = {
  account: 'An open ledger book with numbers and coin stack, financial account',
  act: 'A person on stage performing in spotlight, theatrical act',
  addition: 'Plus sign with two groups of dots combining, math addition',
  adjustment: 'A wrench turning a bolt fine-tuning, adjustment',
  advertisement: 'A billboard poster with megaphone, advertisement',
  agreement: 'Two hands shaking in handshake deal, agreement',
  air: 'Swirling wind breeze lines with cloud, air atmosphere',
  amount: 'A measuring cup filled to level mark, amount quantity',
  amusement: 'A ferris wheel and roller coaster fun park, amusement',
  animal: 'A friendly generic animal paw print, animal kingdom',
  answer: 'A speech bubble with checkmark reply, answer response',
  apparatus: 'Scientific lab equipment beakers and tubes, apparatus',
  approval: 'A green checkmark stamp seal of approval, approval',
  argument: 'Two speech bubbles clashing with lightning, argument debate',
  art: 'An artist palette with paintbrush and colors, art',
  attack: 'A shield blocking an arrow strike, attack defense',
  attempt: 'Abstract concept illustration for attempt (试图): 试图，尝试。用 make an attempt 表示“做一次尝试”。',
  attention: 'A large eye with exclamation alert point, attention focus',
  attraction: 'Abstract concept illustration for attraction (景点): 值得看的地方或事物',
  authority: 'A badge with star and gavel, authority power',
  back: 'A person seen from behind walking away, back rear',
  balance: 'A balance scale perfectly level, balance equilibrium',
  base: 'A pyramid wide foundation base layer, base foundation',
  behavior: 'A person choosing between good and bad path signs, behavior conduct',
  belief: 'A lightbulb inside a thought bubble, belief idea',
  birth: 'A stork delivering baby bundle, birth beginning',
  bit: 'Abstract concept illustration for bit (少量): 少量 —— 用 bit 表示一小部分或一点',
  bite: 'Abstract concept illustration for bite (咬): 咬——用名词 bite 表达咬的动作或痕迹',
  blood: 'A red blood drop with pulse line, blood',
  blow: 'A person blowing out birthday candles, blow breath',
  body: 'A simple human body outline figure, body',
  brass: 'A shiny brass trumpet instrument metal, brass metal',
  bread: 'Abstract concept illustration for bread (面包): 面包 —— 日常主食，用850词表达',
  breath: 'A chest with visible inhale exhale airflow, breath',
  brother: 'Two boys standing together as siblings, brother family',
  building: 'A multi-story office building structure, building construction',
  burn: 'A small campfire flame with logs, burn fire',
  burst: 'A balloon popping with confetti burst, burst explode',
  business: 'A briefcase with tie and chart graph, business commerce',
  butter: 'A stick of yellow butter on plate, butter dairy',
  canvas: 'An artist blank canvas on easel, canvas painting',
  care: 'Gentle hands cupping a small plant seedling, care nurture',
  cause: 'Domino chain reaction first tile falling, cause effect',
  chalk: 'A piece of white chalk writing on board, chalk',
  chance: 'Abstract concept illustration for chance (机会): 机会 —— 用 chance 表达可能性或机遇。',
  change: 'Coins and arrows showing transformation swap, change',
  cloth: 'A folded fabric cloth textile swatch, cloth material',
  coal: 'A lump of black coal rock, coal fuel',
  color: 'A color wheel with rainbow spectrum, color',
  comfort: 'A cozy armchair with warm blanket and tea, comfort',
  committee: 'A round table with several chairs meeting, committee group',
  company: 'A group of people in business attire together, company organization',
  comparison: 'Two bars on chart one taller one shorter, comparison',
  competition: 'Two runners racing toward finish line, competition',
  condition: 'A checklist with status indicators, condition state',
  connection: 'Two puzzle pieces clicking together, connection link',
  control: 'A steering wheel or remote control buttons, control',
  cook: 'A chef stirring pot on stove with ladle, cook',
  copper: 'A copper penny coin reddish metal, copper metal',
  copy: 'Two identical documents side by side, copy duplicate',
  cork: 'A wine bottle with cork stopper pulled, cork',
  cotton: 'A fluffy white cotton boll plant fiber, cotton material',
  cough: 'A person coughing into elbow with motion lines, cough',
  country: 'A map outline with flag and hills, country nation',
  cover: 'A book with protective cover jacket wrapped, cover',
  crack: 'A cracked eggshell with zigzag fracture line, crack',
  credit: 'A credit card with chip and stripe, credit finance',
  crime: 'A magnifying glass over footprints evidence, crime law',
  crush: 'A hand crushing empty soda can flat, crush compress',
  cry: 'A face with tear drops falling down cheeks, cry weep',
  current: 'A river current flowing with arrow direction, current flow',
  curve: 'Abstract concept illustration for curve (曲线): 曲线 —— 用850词描述形状',
  damage: 'A broken vase with crack pieces, damage harm',
  danger: 'A yellow warning triangle exclamation sign, danger hazard',
  daughter: 'A young girl with mother silhouette, daughter family',
  day: 'A bright sun in blue sky daytime scene, day',
  death: 'A wilted flower drooping petals, death end metaphor gentle',
  debt: 'IOU note with owed amount and chain, debt obligation',
  decision: 'A fork in road with two path signs, decision choice',
  degree: 'A thermometer showing temperature degree mark, degree measurement',
  design: 'Blueprint drafting compass and ruler plan, design',
  desire: 'A heart with reaching hand toward star, desire want',
  destruction: 'A demolished building rubble pile, destruction ruin',
  detail: 'A magnifying glass over fine intricate pattern, detail',
  development: 'A seedling growing through stages to tree, development growth',
  digestion: 'Abstract concept illustration for digestion (消化): 消化：食物在身体里变成能量的过程。',
  direction: 'A compass rose pointing north south east west, direction navigation',
  discovery: 'A treasure chest opened with light beam, discovery find',
  discussion: 'Two people talking with speech bubbles, discussion talk',
  disease: 'A virus germ cell with spiky surface, disease illness',
  disgust: 'A face wrinkling nose at spoiled food, disgust reaction',
  distance: 'Two landmarks far apart with dotted measure line, distance',
  distribution: 'Boxes being spread from central warehouse, distribution spread',
  division: 'A pie chart sliced into equal parts, division split',
  doubt: 'A person with question marks floating around head, doubt uncertainty',
  drink: 'A glass of water with straw, drink beverage',
  driving: 'Hands on steering wheel of car, driving',
  dust: 'Floating dust particles in sunbeam light, dust',
  earth: 'Planet Earth globe showing continents, earth planet',
  edge: 'A cliff edge overlooking drop, edge border',
  education: 'A graduation cap mortarboard with diploma, education learning',
  effect: 'Ripples spreading from stone dropped in water, effect result',
  end: 'A finish line banner ribbon endpoint, end conclusion',
  error: 'A red X mark on wrong answer paper, error mistake',
  event: 'A calendar date circled with star event marker, event occasion',
  example: 'A sample specimen in display case labeled, example model',
  exchange: 'Two arrows swapping items between hands, exchange trade',
  existence: 'A single tree standing alone in field, existence being',
  expansion: 'An inflating balloon growing larger, expansion growth',
  experience: 'A person climbing mountain reaching summit, experience journey',
  expert: 'A person with medal and certificate expertise badge, expert',
  fact: 'A document with verified checkmark stamp FACT, fact truth',
  fall: 'Autumn leaves falling from tree, fall season drop',
  family: 'A family group parents and children together, family',
  father: 'A father figure with child on shoulders, father parent',
  fear: 'A person hiding behind shield from shadow, fear afraid',
  feeling: 'A heart with mixed emotion color waves, feeling emotion',
  fiction: 'An open storybook with dragon and castle fantasy, fiction story',
  field: 'A green farm field with crops rows, field meadow',
  fight: 'Two boxing gloves facing each other, fight conflict',
  fire: 'Orange and red campfire flames, fire',
  flame: 'A single candle flame flickering, flame fire',
  flight: 'A bird or plane soaring in sky trail, flight flying',
  flower: 'A colorful blooming flower with stem, flower plant',
  fold: 'A piece of paper folded in half crease, fold bend',
  food: 'A plate with bread fruit and vegetables, food meal',
  force: 'A strong arm pushing heavy boulder, force power',
  form: 'Clay being shaped on pottery wheel into vase, form shape',
  friend: 'Two people high-fiving as friends, friendship',
  front: 'Front view of house with door facing viewer, front forward',
  fruit: 'A bowl of assorted colorful fruits, fruit food',
  glass: 'A clear drinking glass half full of water, glass container',
  gold: 'A gold bar ingot shining yellow metal, gold precious',
  government: 'A capitol building with dome and flag, government',
  grain: 'Wheat grain stalks bundle harvest, grain cereal',
  grass: 'Green grass blades patch on ground, grass plant',
  grip: 'Abstract concept illustration for grip (紧握/抓力): 紧握/抓力 —— 用 grip 表示握住或控制',
  group: 'A circle of people holding hands together, group team',
  growth: 'A small plant sprout growing taller with arrow up, growth increase',
  guide: 'A tour guide pointing with flag on stick, guide leader',
  harbor: 'A ship docked at harbor with lighthouse, harbor port',
  harmony: 'Musical notes flowing in peaceful wave pattern, harmony peace',
  hate: 'A broken heart cracked in half dark, hate dislike',
  hearing: 'A large ear with sound wave lines incoming, hearing listen',
  heat: 'Abstract concept illustration for heat (热): 热 —— 温度或情绪上的热度',
  help: 'One hand helping pull another person up cliff, help assist',
  history: 'An old scroll parchment with quill pen, history past',
  hole: 'A round hole dug in ground showing depth, hole opening',
  hope: 'A small green shoot growing through crack in concrete, hope optimism',
  hour: 'Abstract concept illustration for hour (小时): 小时 —— 时间单位，日常、工作、抽象场景都能用。',
  humor: 'A laughing face with comedy mask, humor funny',
  ice: 'An ice cube melting with cold vapor, ice frozen',
  idea: 'A glowing lightbulb above head moment, idea thought',
  impulse: 'Abstract concept illustration for impulse (冲动): 冲动 —— 用 impulse 表达一时兴起或内在驱动。',
  increase: 'An upward trending arrow chart line growing, increase rise',
  industry: 'Factory smokestacks and gears industrial scene, industry manufacturing',
  ink: 'An ink bottle with quill pen dripping, ink writing',
  insect: 'A colorful butterfly insect with wings, insect bug',
  instrument: 'A violin musical instrument with bow, instrument tool',
  insurance: 'An umbrella shielding house from rain storm, insurance protection',
  interest: 'A person reading book with curious wide eyes, interest curiosity',
  invention: 'A gear lightbulb prototype gadget workshop, invention create',
  iron: 'A flatiron pressing clothes with steam, iron metal tool',
  jelly: 'A wobbly jelly dessert in bowl quivering, jelly food',
  join: 'Two chain links connecting together, join connect',
  journey: 'A winding path through hills with footprints, journey travel',
  judge: 'A judge gavel on wooden block bench, judge law',
  jump: 'A person mid-air jumping over puddle, jump leap',
  kick: 'A foot kicking soccer ball, kick strike',
  kiss: 'Two faces about to kiss with heart, kiss affection',
  knowledge: 'A brain with books and graduation cap, knowledge learning',
  land: 'Green land terrain with hills and trees, land ground',
  language: 'Speech bubbles with ABC letters different scripts, language',
  laugh: 'A face laughing with open mouth joy, laugh humor',
  law: 'Scales of justice with law book, law legal',
  lead: 'A person leading group pointing forward path, lead guide',
  learning: 'Open textbook with pencil and lightbulb, learning study',
  leather: 'A brown leather wallet or belt texture, leather material',
  letter: 'A sealed envelope with stamp mail letter, letter mail',
  level: 'A spirit level tool showing bubble centered, level flat',
  lift: 'An elevator lift car in shaft going up, lift raise',
  light: 'A bright glowing lightbulb radiating beams, light illumination',
  limit: 'A road barrier stop sign boundary line, limit boundary',
  linen: 'Folded white linen bedsheet fabric texture, linen cloth',
  liquid: 'A pouring water stream into glass, liquid fluid',
  list: 'A numbered checklist on clipboard paper, list',
  look: 'A pair of eyes looking through binoculars, look see',
  loss: 'An empty wallet turned upside down, loss lose',
  love: 'A red heart with sparkles radiating warmth, love affection',
  machine: 'Gears and cogs mechanical machine assembly, machine device',
  man: 'A simple adult man standing figure, man person',
  manager: 'A person at desk with organizational chart, manager boss',
  mark: 'A checkmark pen marking paper, mark sign',
  market: 'A market stall with fruits and price sign, market shop',
  mass: 'A crowd of many people gathered together, mass group',
  meal: 'A dinner plate with fork knife and food served, meal dining',
  measure: 'A ruler measuring length of object, measure size',
  meat: 'A steak cut of meat on cutting board, meat food',
  meeting: 'People sitting around conference table talking, meeting gather',
  memory: 'A photo album with nostalgic pictures, memory remember',
  metal: 'Shiny metal ingots and bolts stacked, metal material',
  middle: 'A line with dot exactly in center midpoint, middle center',
  milk: 'A glass bottle of white milk, milk dairy',
  mind: 'A head silhouette with brain gears thinking, mind thought',
  mine: 'Abstract concept illustration for mine (矿): 矿：地下挖出的煤炭或金属',
  minute: 'A clock showing one minute hand tick, minute time',
  mist: 'Fog mist over lake morning hazy scene, mist fog',
  money: 'Stack of coins and paper bills currency, money cash',
  month: 'A calendar page showing month grid, month time',
  morning: 'Sunrise over horizon with rooster and coffee, morning dawn',
  mother: 'A mother holding baby tenderly, mother parent',
  motion: 'Motion blur lines showing object moving fast, motion movement',
  mountain: 'A tall snow-capped mountain peak landscape, mountain',
  move: 'A cardboard box being carried with arrow path, move relocate',
  music: 'Musical notes floating from headphones, music sound',
  name: 'A name tag badge with blank label, name identity',
  nation: 'A country map outline with flag pole, nation country',
  need: 'An empty plate with fork and hungry expression, need necessity',
  news: 'A newspaper front page with headline, news information',
  night: 'A crescent moon and stars dark sky, night evening',
  noise: 'Sound wave zigzag lines with speaker loud, noise sound',
  note: 'A sticky note with pencil writing reminder, note memo',
  number: 'Large digit numbers 1 2 3 floating, number count',
  observation: 'A person with telescope looking at stars, observation watch',
  offer: 'Hands presenting wrapped gift offering forward, offer give',
  oil: 'An oil barrel or olive oil bottle golden liquid, oil',
  operation: 'Surgeon tools on sterile tray medical, operation procedure',
  opinion: 'A thought bubble with thumbs up and down, opinion view',
  order: 'Abstract concept illustration for order (命令): 排好的次序 —— give an order。',
  organization: 'An org chart tree diagram hierarchy boxes, organization structure',
  ornament: 'A decorative Christmas ornament ball hanging, ornament decoration',
  owner: 'A person holding house key with property deed, owner possession',
  page: 'An open book page with text lines, page sheet',
  pain: 'A bandaid on knee with ouch expression, pain hurt',
  paint: 'Paint brush dipping into colorful paint cans, paint color',
  paper: 'A stack of white paper sheets, paper material',
  part: 'A jigsaw puzzle piece separated from whole, part piece',
  paste: 'A tube of glue paste squeezing out, paste adhesive',
  payment: 'A hand passing coin to another hand transaction, payment pay',
  peace: 'A white dove carrying olive branch, peace calm',
  person: 'A simple stick figure person standing, person human',
  place: 'A map pin marking a specific location spot, place location',
  plant: 'A potted green houseplant on windowsill, plant vegetation',
  play: 'Children playing with ball in playground, play fun',
  pleasure: 'A smiling face with sun and ice cream joy, pleasure enjoyment',
  point: 'A finger pointing at specific dot target, point indicate',
  poison: 'A bottle with skull crossbones warning label, poison toxic',
  polish: 'A shoe being polished to shine with brush, polish shine',
  porter: 'A person carrying luggage bags at hotel, porter carrier',
  position: 'A chess piece on specific board square, position place',
  powder: 'A pile of fine white powder dust, powder substance',
  power: 'A lightning bolt striking with electric energy, power strength',
  price: 'A price tag label with dollar amount, price cost',
  print: 'A printer printing document page output, print',
  process: 'Factory conveyor belt with steps flowchart arrows, process procedure',
  produce: 'A farmer basket of fresh harvested vegetables, produce food',
  profit: 'A chart arrow going up with coin stack gain, profit earnings',
  property: 'A house deed document with key, property ownership',
  prose: 'An open novel book with flowing text paragraphs, prose writing',
  protest: 'People holding protest signs marching together, protest oppose',
  pull: 'A hand pulling rope with effort strain, pull drag',
  punishment: 'A dunce cap on stool corner time-out, punishment discipline gentle',
  purpose: 'A target bullseye with arrow hitting center goal, purpose aim',
  push: 'Hands pushing heavy box across floor, push shove',
  quality: 'A gold star badge excellence seal, quality standard',
  question: 'A large question mark floating with curious face, question ask',
  rain: 'Rain clouds with falling raindrops, rain weather',
  range: 'Abstract concept illustration for range (范围): 范围 —— 用 range 表示一片区域或一组数值。',
  rate: 'Abstract concept illustration for rate (速度): 速度——用 rate 表示快慢程度。',
  ray: 'Abstract concept illustration for ray (射线): 射线 —— 光或热的一条线',
  reaction: 'A chemical flask bubbling colorful reaction, reaction response',
  reading: 'A person reading open book comfortably, reading',
  reason: 'A brain connected to lightbulb logic chain, reason logic',
  record: 'A vinyl record disc on turntable, record document',
  regret: 'A person looking back at closed door sadly, regret sorrow',
  relation: 'A family tree diagram connecting relatives, relation family',
  religion: 'Hands clasped in prayer with soft light, religion faith',
  representative: 'A person speaking at podium with flag, representative delegate',
  request: 'Hands together asking please with speech bubble, request ask',
  respect: 'A bow of respect or salute gesture honor, respect honor',
  rest: 'A person resting on hammock with closed eyes, rest relax',
  reward: 'A gold trophy medal prize ribbon, reward prize',
  rhythm: 'Musical notes in repeating beat pattern wave, rhythm beat',
  rice: 'A bowl of white steamed rice with chopsticks, rice grain',
  river: 'A winding blue river through green valley, river water',
  road: 'A road stretching to horizon with dashed lines, road path',
  roll: 'A bread roll or toilet paper roll cylinder, roll rotate',
  room: 'A furnished bedroom with bed and lamp, room space',
  rub: 'Hands rubbing together creating warmth friction, rub friction',
  rule: 'A ruler and list of rules on paper, rule regulation',
  run: 'A person running with motion speed lines, run jog',
  salt: 'A salt shaker sprinkling white crystals, salt seasoning',
  sand: 'A beach sand pile with small shell, sand grain',
  scale: 'A bathroom weight scale showing measurement, scale size measure',
  science: 'A microscope and atom model laboratory, science research',
  sea: 'Ocean waves with sailboat on blue water, sea ocean',
  seat: 'A wooden chair seat empty waiting, seat sit',
  secretary: 'A desk with typewriter calendar and files organized, secretary office',
  selection: 'A hand choosing one item from multiple options, selection choose',
  self: 'A mirror reflection showing same person, self identity',
  sense: 'Five icons eye ear nose tongue hand for senses, sense perception',
  servant: 'A person serving tray of food politely, servant serve',
  sex: 'Male and female gender symbols simple abstract, sex gender',
  shade: 'A tree casting cool shadow on ground, shade shadow',
  shake: 'Two hands shaking or salt shaker shaking, shake tremble',
  shame: 'A face blushing red covering eyes embarrassed, shame embarrassed',
  shock: 'A face with wide eyes and lightning bolt surprise, shock surprise',
  side: 'An object shown from side profile view, side lateral',
  sign: 'A wooden signpost with arrow directions, sign signal',
  silk: 'A flowing silk fabric scarf draping softly, silk fabric',
  silver: 'Abstract concept illustration for silver (银): 银——BE850唯一金属名词',
  sister: 'Two girls standing together as siblings, sister family',
  size: 'Three objects small medium large comparison, size dimension',
  sky: 'Blue sky with white fluffy clouds panorama, sky atmosphere',
  sleep: 'A person sleeping peacefully in bed with Zzz, sleep rest',
  slip: 'A foot slipping on banana peel cartoon, slip slide',
  slope: 'A hillside slope with ball rolling down angle, slope incline',
  smash: 'A hammer smashing pumpkin into pieces, smash break',
  smell: 'A nose sniffing fragrant flower aroma waves, smell scent',
  smile: 'A happy face with big warm smile, smile happy',
  smoke: 'Gray smoke rising from chimney curl wisps, smoke',
  sneeze: 'A face sneezing with tissue and spray dots, sneeze',
  snow: 'Snowflakes falling on snowman winter scene, snow weather',
  soap: 'A bar of soap with bubbles lather, soap clean',
  society: 'A city skyline with diverse people community, society community',
  son: 'A young boy with father figure together, son family',
  song: 'Musical notes with microphone singing, song music',
  sort: 'Items being sorted into labeled bins categories, sort organize',
  sound: 'Speaker emitting visible sound wave rings, sound audio',
  soup: 'A steaming bowl of vegetable soup with spoon, soup food',
  space: 'Outer space with planets stars and astronaut, space cosmos',
  stage: 'A theater stage with red curtains and spotlight, stage platform',
  start: 'A green traffic light GO starting flag, start begin',
  statement: 'A formal document with quoted text lines, statement declare',
  steam: 'A kettle releasing white steam vapor cloud, steam vapor',
  steel: 'Steel I-beam construction metal girder, steel metal',
  step: 'Footprints on staircase steps going up, step stair',
  stitch: 'A needle pulling thread through fabric sewing, stitch sew',
  stone: 'A smooth gray river stone rock, stone rock',
  stop: 'A red octagonal STOP sign hand raised, stop halt',
  story: 'An open storybook with castle illustration, story tale',
  stretch: 'A person stretching arms overhead yawning, stretch extend',
  structure: 'A building frame skeleton under construction, structure framework',
  substance: 'A laboratory flask with colorful chemical liquid, substance material',
  sugar: 'White sugar cubes and granules in bowl, sugar sweet',
  suggestion: 'A lightbulb appearing in speech bubble hint, suggestion idea',
  summer: 'A bright sun beach umbrella and sunglasses summer, summer season',
  support: 'A pillar holding up roof structure beam, support hold',
  surprise: 'A gift box popping open with confetti surprise, surprise astonish',
  swim: 'A person swimming in pool with goggles, swim water',
  system: 'Connected gears and nodes network diagram flow, system organization',
  talk: 'Two people conversing with speech bubbles, talk speak',
  taste: 'A tongue tasting food with flavor stars, taste flavor',
  tax: 'A receipt with tax percentage calculation coins, tax payment',
  teaching: 'A teacher at chalkboard explaining to students, teaching education',
  tendency: 'An arrow showing gradual trend direction curve, tendency trend',
  test: 'A pencil filling in test exam answer sheet, test exam',
  theory: 'A chalkboard with equation and thought experiment, theory idea',
  thing: 'A generic cardboard box mystery item, thing object',
  thought: 'A cloud thought bubble with dots thinking, thought idea',
  thunder: 'Lightning bolt with dark storm cloud rumble, thunder storm',
  time: 'An hourglass with sand flowing through, time clock',
  tin: 'A tin can container with lid, tin metal',
  top: 'An arrow pointing to top of mountain peak summit, top highest',
  touch: 'A fingertip touching screen ripple effect, touch feel',
  trade: 'Two merchants exchanging goods at market stall, trade commerce',
  transport: 'A truck carrying boxes on highway delivery, transport carry',
  trick: 'A magician pulling rabbit from hat trick, trick deception',
  trouble: 'A person tangled in messy knot string problem, trouble difficulty',
  turn: 'A curved arrow showing rotation turning direction, turn rotate',
  twist: 'A rope being twisted into spiral shape, twist wind',
  unit: 'A single building block unit in stack, unit piece',
  use: 'A hand using tool wrench on bolt purposefully, use utilize',
  value: 'A diamond gem on price scale weighing worth, value worth',
  verse: 'Poetry lines on parchment with quill, verse poetry',
  vessel: 'A ship sailing on ocean water vessel, vessel container',
  view: 'Binoculars looking at scenic mountain vista, view scenery',
  voice: 'Sound waves emanating from open mouth singing, voice sound',
  walk: 'A person walking on sidewalk with footprints, walk stroll',
  war: 'Crossed swords or broken peace dove metaphor, war conflict',
  wash: 'Hands washing with soap bubbles under faucet, wash clean',
  waste: 'A trash bin overflowing with discarded items, waste garbage',
  water: 'A clear water drop splash ripple, water liquid',
  wave: 'An ocean wave curling with white foam, wave water',
  wax: 'A burning candle with dripping wax, wax material',
  way: 'A forked path road sign choosing route, way path method',
  weather: 'Sun cloud rain umbrella combined weather icons, weather climate',
  week: 'A calendar showing seven days of week row, week time',
  weight: 'A dumbbell weight on scale heavy, weight mass',
  wind: 'Swirling wind lines bending tree branches, wind breeze',
  wine: 'A wine glass with red liquid grape bunch, wine drink',
  winter: 'A snowflake icicle bare tree winter scene, winter season',
  woman: 'A simple adult woman standing figure, woman person',
  wood: 'A log wood grain texture plank, wood timber',
  wool: 'Abstract concept illustration for wool (羊毛): 羊毛 —— 保暖、柔软，来自羊的毛。',
  word: 'Letters ABC forming the word in speech bubble, word language',
  work: 'A person at desk with laptop working, work job',
  wound: 'A bandaged arm with medical cross care, wound injury',
  writing: 'A hand writing with pen on paper lines, writing',
  year: 'A calendar flipping through twelve months year cycle, year time',
};

export const QUALITY_PROMPTS: Record<string, string> = {
  able: 'A strong arm flexing muscle showing capability, able capable',
  acid: 'A test tube with bubbling green acidic liquid, acid chemical',
  angry: 'A red face with furrowed brows and steam from ears, angry emotion',
  automatic: 'A gear mechanism running by itself without hand, automatic self',
  beautiful: 'A blooming rose flower radiant and lovely, beautiful pretty',
  black: 'A solid black circle fill color swatch, black color',
  boiling: 'Visual metaphor for boiling (沸腾的): 形容「沸腾的」—— 放在名词前面。',
  bright: 'A shining sun with radiant light beams bright, bright luminous',
  broken: 'Visual metaphor for broken (破碎的): 形容「破碎的」—— 放在名词前面。',
  brown: 'A solid brown circle fill color swatch, brown color',
  cheap: 'Visual metaphor for cheap (便宜的): 形容「便宜的」—— 放在名词前面。',
  chemical: 'Visual metaphor for chemical (化学的): 形容「化学的」—— 放在名词前面。',
  chief: 'A golden crown on top of group leader, chief main',
  clean: 'Sparkling clean surface with shine stars, clean pure',
  clear: 'A transparent crystal clear glass sphere, clear transparent',
  common: 'Visual metaphor for common (常见的): 形容「常见的」—— 放在名词前面。',
  complex: 'Interlocking gears and maze pattern intricate, complex complicated',
  conscious: 'An open eye with awareness light rays, conscious aware',
  cut: 'Visual metaphor for cut (切割的): 形容「切割的」—— 放在名词前面。',
  deep: 'Visual metaphor for deep (深的): 形容「深的」—— 放在名词前面。',
  dependent: 'Visual metaphor for dependent (依赖的): 形容「依赖的」—— 放在名词前面。',
  early: 'Visual metaphor for early (早的): 形容「早的」—— 放在名词前面。',
  elastic: 'Visual metaphor for elastic (有弹性的): 形容「有弹性的」—— 放在名词前面。',
  electric: 'Visual metaphor for electric (电的): 形容「电的」—— 放在名词前面。',
  equal: 'Visual metaphor for equal (相等的): 形容「相等的」—— 放在名词前面。',
  fat: 'A round plump circle shape full, fat thick',
  fertile: 'Rich green soil with sprouting seeds abundant, fertile productive',
  first: 'A gold medal number one first place podium, first initial',
  fixed: 'A bolt screwed tight immovable locked position, fixed stationary',
  flat: 'A perfectly flat horizon line level surface, flat even',
  free: 'Visual metaphor for free (自由的): 形容「自由的」—— 放在名词前面。',
  frequent: 'Visual metaphor for frequent (频繁的): 形容「频繁的」—— 放在名词前面。',
  full: 'A glass filled to brim overflowing, full complete',
  general: 'Visual metaphor for general (一般的): 形容「一般的」—— 放在名词前面。',
  good: 'A green thumbs up with warm glow, good positive',
  great: 'A large golden star trophy excellence, great excellent',
  grey: 'A solid grey circle fill color swatch, gray color',
  hanging: 'An object dangling from rope hook suspended, hanging suspended',
  happy: 'A smiling yellow sun face with joy rays, happy cheerful',
  hard: 'A diamond hard rock unscratchable surface, hard solid',
  healthy: 'A green apple with heart pulse line vitality, healthy fit',
  high: 'A tall tower reaching high into clouds, high elevated',
  hollow: 'A empty eggshell hollow inside visible, hollow empty inside',
  important: 'A large exclamation mark with star priority badge, important significant',
  kind: 'Gentle hands offering flower gift kindness, kind gentle',
  like: 'A heart with thumbs up approval fondness, like enjoy',
  living: 'A green sprouting seedling with pulse of life, living alive',
  long: 'A very long snake or ruler stretched out, long length',
  male: 'A simple male gender symbol Mars sign, male man',
  married: 'Two wedding rings interlocked together, married wed',
  material: 'Visual metaphor for material (材料的): 形容「材料的」—— 放在名词前面。',
  medical: 'Visual metaphor for medical (医学的): 形容「医学的」—— 放在名词前面。',
  military: 'Visual metaphor for military (军事的): 形容「军事的」—— 放在名词前面。',
  natural: 'A leaf and flower growing wild outdoors, natural organic',
  necessary: 'A required checklist item with red asterisk must, necessary needed',
  new: 'A shiny gift box with NEW tag ribbon, new fresh',
  normal: 'An average typical house on ordinary street, normal standard',
  open: 'An open door welcoming with light streaming in, open unlocked',
  parallel: 'Two parallel train tracks running same direction, parallel aligned',
  past: 'An hourglass with sand mostly fallen bottom past, past gone',
  physical: 'Muscles and fitness body silhouette strong, physical bodily',
  political: 'A voting ballot with government building dome, political civic',
  poor: 'An empty wallet turned inside out, poor lacking',
  possible: 'An open door with bright opportunity light ahead, possible achievable',
  present: 'A wrapped gift box being presented now, present current gift',
  private: 'A closed lock on personal diary book, private secret',
  probable: 'A dice showing likely outcome percentage bar, probable likely',
  quick: 'A rabbit running fast with speed lines, quick fast',
  quiet: 'A finger on lips shushing silence gesture, quiet silent',
  ready: 'A runner at starting blocks poised to go, ready prepared',
  red: 'A solid red circle fill color swatch, red color',
  regular: 'A calendar with repeating same pattern schedule, regular routine',
  responsible: 'A person carrying important task checklist dutifully, responsible accountable',
  right: 'A green checkmark correct direction arrow, right correct',
  round: 'A perfect round circle sphere shape, round circular',
  same: 'Two identical matching twin objects, same equal',
  second: 'A silver medal number two second place, second next',
  separate: 'Two objects pulled apart with gap between, separate apart',
  serious: 'A stern face with focused intense expression, serious grave',
  sharp: 'A sharp knife blade point cutting edge, sharp pointed',
  smooth: 'A smooth polished marble surface reflective, smooth even',
  sticky: 'Honey dripping sticky glue strands stretchy, sticky adhesive',
  stiff: 'A rigid board that will not bend, stiff rigid',
  straight: 'A perfectly straight ruler line edge, straight direct',
  strong: 'A muscular arm lifting heavy weight, strong powerful',
  sudden: 'A lightning bolt sudden flash surprise, sudden abrupt',
  sweet: 'A honey dipper dripping golden sweetness, sweet sugary',
  tall: 'A giraffe or tall building reaching sky, tall high',
  thick: 'A thick stack of books heavy volume, thick dense',
  tight: 'A tightly wound rope knot secure firm, tight snug',
  tired: 'A person yawning with heavy droopy eyes, tired exhausted',
  true: 'A green verified checkmark authentic seal, true real',
  violent: 'A storm with lightning and crashing waves intense, violent forceful',
  waiting: 'A person sitting on bench looking at watch waiting, waiting expect',
  warm: 'A cozy fireplace with warm orange glow, warm heated',
  wet: 'Water droplets on surface dripping wet, wet moist',
  wide: 'A wide open landscape panorama broad view, wide broad',
  wise: 'An owl with glasses and book wisdom, wise smart',
  yellow: 'A solid yellow circle fill color swatch, yellow color',
  young: 'A small seedling sprout new growth young, young youthful',
};

export const OPPOSITE_PROMPTS: Record<string, string> = {
  awake: 'A wide open eye alert and bright awake, opposite of sleep',
  bad: 'A wilted rotten apple with flies dark, bad negative quality',
  bent: 'A bent crooked nail not straight angled, bent curved',
  bitter: 'A lemon face wincing sour bitter taste, bitter taste',
  blue: 'A sad blue face with tear drop melancholy, blue sad mood',
  certain: 'A confident solid checkmark seal sure, certain sure',
  cold: 'Blue icicles frozen thermometer low cold, cold temperature',
  complete: 'A full complete puzzle all pieces fitted, complete whole',
  cruel: 'Sharp thorns crushing delicate flower cruel, cruel harsh',
  dark: 'A moonless dark night silhouette scene, dark dim',
  dead: 'A brown fallen leaf still on ground, dead not living',
  dear: 'Clear visual for opposite quality dear (亲爱的)',
  delicate: 'Clear visual for opposite quality delicate (精细的)',
  different: 'Circle and square different shapes contrast, different unlike',
  dirty: 'Muddy messy splatters on clean surface, dirty unclean',
  dry: 'Cracked parched earth no moisture dry, dry arid',
  false: 'A red X on false wrong claim, false untrue',
  feeble: 'A thin weak wilting stem barely standing, feeble weak',
  female: 'Female Venus gender symbol sign, female woman',
  foolish: 'A jester hat with silly confused expression, foolish silly',
  future: 'A crystal ball showing tomorrow ahead arrow, future ahead time',
  green: 'Clear visual for opposite quality green (绿色的)',
  ill: 'Thermometer fever sick face with tissue, ill sick',
  last: 'Finish line flag last position end, last final',
  late: 'Clock running behind schedule late time, late delayed',
  left: 'Left pointing arrow on left side, left direction',
  loose: 'Untied loose shoelace dangling free, loose not tight',
  loud: 'Megaphone blasting loud sound waves, loud noisy',
  low: 'Valley low point below mountain level, low short',
  mixed: 'Swirl of blended mixed colors together, mixed combined',
  narrow: 'Narrow tight alley between buildings, narrow thin',
  old: 'Weathered old tree with aged bark, old aged',
  opposite: 'Two arrows pointing opposite apart directions, opposite contrary',
  public: 'Clear visual for opposite quality public (公众的)',
  rough: 'Rough sandpaper gritty texture surface, rough coarse',
  sad: 'Blue rain cloud drooping sad face tears, sad unhappy',
  safe: 'Shield with checkmark safe protected, safe secure',
  secret: 'Clear visual for opposite quality secret (秘密的)',
  short: 'Short stubby pencil vs long comparison, short brief',
  shut: 'Closed shut door locked tight, shut closed',
  simple: 'Clear visual for opposite quality simple (简单的)',
  slow: 'Turtle crawling slowly with clock, slow gradual',
  small: 'Tiny ant next to elephant small, small little',
  soft: 'Fluffy soft cloud pillow texture, soft gentle',
  solid: 'Solid dense cube block unbreakable, solid firm',
  special: 'Gold star badge unique special sparkle, special particular',
  strange: 'Unusual alien plant strange odd, strange unusual',
  thin: 'Thin transparent paper sheet slim, thin slim',
  white: 'Single clear illustration of white pole contrasted subtly with black, opposite concept',
  wrong: 'Red X wrong answer crossed out, wrong incorrect',
};

/** 全量合并表 */
export const ALL_WORD_PNG_PROMPTS: Record<string, string> = {
  ...OPERATOR_PROMPTS,
  ...PICTURABLE_PROMPTS,
  ...DIRECTION_PROMPTS,
  ...GENERAL_PROMPTS,
  ...QUALITY_PROMPTS,
  ...OPPOSITE_PROMPTS,
};

export function buildPrompt(word: string, semantic?: string): string {
  const sem = semantic ?? ALL_WORD_PNG_PROMPTS[word.toLowerCase()] ?? word;
  return `${sem}. ${WORD_ILLUSTRATION_STYLE}`;
}
